# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import arikedbpbuff_pb2 as arikedbpbuff__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in arikedbpbuff_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ArikedbRPCStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollections = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/CreateCollections',
                request_serializer=arikedbpbuff__pb2.CreateCollectionsRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.CreateCollectionsResponse.FromString,
                _registered_method=True)
        self.DeleteCollections = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/DeleteCollections',
                request_serializer=arikedbpbuff__pb2.DeleteCollectionsRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.DeleteCollectionsResponse.FromString,
                _registered_method=True)
        self.ListCollections = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/ListCollections',
                request_serializer=arikedbpbuff__pb2.ListCollectionsRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.ListCollectionsResponse.FromString,
                _registered_method=True)
        self.CreateVariables = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/CreateVariables',
                request_serializer=arikedbpbuff__pb2.CreateVariablesRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.CreateVariablesResponse.FromString,
                _registered_method=True)
        self.DeleteVariables = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/DeleteVariables',
                request_serializer=arikedbpbuff__pb2.DeleteVariablesRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.DeleteVariablesResponse.FromString,
                _registered_method=True)
        self.ListVariables = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/ListVariables',
                request_serializer=arikedbpbuff__pb2.ListVariablesRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.ListVariablesResponse.FromString,
                _registered_method=True)
        self.SetVariables = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/SetVariables',
                request_serializer=arikedbpbuff__pb2.SetVariablesRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.SetVariablesResponse.FromString,
                _registered_method=True)
        self.GetVariables = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/GetVariables',
                request_serializer=arikedbpbuff__pb2.GetVariablesRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.GetVariablesResponse.FromString,
                _registered_method=True)
        self.SubscribeVariables = channel.unary_stream(
                '/arikedbpbuff.ArikedbRPC/SubscribeVariables',
                request_serializer=arikedbpbuff__pb2.SubscribeVariablesRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.VarDataPoint.FromString,
                _registered_method=True)
        self.Authenticate = channel.unary_unary(
                '/arikedbpbuff.ArikedbRPC/Authenticate',
                request_serializer=arikedbpbuff__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=arikedbpbuff__pb2.AuthenticateResponse.FromString,
                _registered_method=True)


class ArikedbRPCServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCollections(self, request, context):
        """Global Server rpc methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCollections(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateVariables(self, request, context):
        """Collection rpc methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeVariables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authenticate(self, request, context):
        """Auth
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArikedbRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollections,
                    request_deserializer=arikedbpbuff__pb2.CreateCollectionsRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.CreateCollectionsResponse.SerializeToString,
            ),
            'DeleteCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollections,
                    request_deserializer=arikedbpbuff__pb2.DeleteCollectionsRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.DeleteCollectionsResponse.SerializeToString,
            ),
            'ListCollections': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCollections,
                    request_deserializer=arikedbpbuff__pb2.ListCollectionsRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.ListCollectionsResponse.SerializeToString,
            ),
            'CreateVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVariables,
                    request_deserializer=arikedbpbuff__pb2.CreateVariablesRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.CreateVariablesResponse.SerializeToString,
            ),
            'DeleteVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVariables,
                    request_deserializer=arikedbpbuff__pb2.DeleteVariablesRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.DeleteVariablesResponse.SerializeToString,
            ),
            'ListVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVariables,
                    request_deserializer=arikedbpbuff__pb2.ListVariablesRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.ListVariablesResponse.SerializeToString,
            ),
            'SetVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.SetVariables,
                    request_deserializer=arikedbpbuff__pb2.SetVariablesRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.SetVariablesResponse.SerializeToString,
            ),
            'GetVariables': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVariables,
                    request_deserializer=arikedbpbuff__pb2.GetVariablesRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.GetVariablesResponse.SerializeToString,
            ),
            'SubscribeVariables': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeVariables,
                    request_deserializer=arikedbpbuff__pb2.SubscribeVariablesRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.VarDataPoint.SerializeToString,
            ),
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=arikedbpbuff__pb2.AuthenticateRequest.FromString,
                    response_serializer=arikedbpbuff__pb2.AuthenticateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'arikedbpbuff.ArikedbRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('arikedbpbuff.ArikedbRPC', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArikedbRPC(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/CreateCollections',
            arikedbpbuff__pb2.CreateCollectionsRequest.SerializeToString,
            arikedbpbuff__pb2.CreateCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/DeleteCollections',
            arikedbpbuff__pb2.DeleteCollectionsRequest.SerializeToString,
            arikedbpbuff__pb2.DeleteCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCollections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/ListCollections',
            arikedbpbuff__pb2.ListCollectionsRequest.SerializeToString,
            arikedbpbuff__pb2.ListCollectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/CreateVariables',
            arikedbpbuff__pb2.CreateVariablesRequest.SerializeToString,
            arikedbpbuff__pb2.CreateVariablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/DeleteVariables',
            arikedbpbuff__pb2.DeleteVariablesRequest.SerializeToString,
            arikedbpbuff__pb2.DeleteVariablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/ListVariables',
            arikedbpbuff__pb2.ListVariablesRequest.SerializeToString,
            arikedbpbuff__pb2.ListVariablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/SetVariables',
            arikedbpbuff__pb2.SetVariablesRequest.SerializeToString,
            arikedbpbuff__pb2.SetVariablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/GetVariables',
            arikedbpbuff__pb2.GetVariablesRequest.SerializeToString,
            arikedbpbuff__pb2.GetVariablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeVariables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/SubscribeVariables',
            arikedbpbuff__pb2.SubscribeVariablesRequest.SerializeToString,
            arikedbpbuff__pb2.VarDataPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/arikedbpbuff.ArikedbRPC/Authenticate',
            arikedbpbuff__pb2.AuthenticateRequest.SerializeToString,
            arikedbpbuff__pb2.AuthenticateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
