# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arike_collection.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'arike_collection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import arikedb.arike_utils_pb2 as arike__utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61rike_collection.proto\x12\x08\x61rike_pb\x1a\x11\x61rike_utils.proto\"\x1e\n\x0e\x43ollectionMeta\x12\x0c\n\x04name\x18\x01 \x01(\t\"I\n\x18\x43reateCollectionsRequest\x12-\n\x0b\x63ollections\x18\x01 \x03(\x0b\x32\x18.arike_pb.CollectionMeta\"s\n\x19\x43reateCollectionsResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.arike_pb.StatusCode\x12\x16\n\x0e\x61lready_exists\x18\x02 \x03(\t\x12\x18\n\x10license_exceeded\x18\x03 \x03(\t\")\n\x18\x44\x65leteCollectionsRequest\x12\r\n\x05names\x18\x01 \x03(\t\"T\n\x19\x44\x65leteCollectionsResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.arike_pb.StatusCode\x12\x11\n\tnot_found\x18\x02 \x03(\t\":\n\x16ListCollectionsRequest\x12\x14\n\x07pattern\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_pattern\"n\n\x17ListCollectionsResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.arike_pb.StatusCode\x12-\n\x0b\x63ollections\x18\x02 \x03(\x0b\x32\x18.arike_pb.CollectionMetab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arike_collection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COLLECTIONMETA']._serialized_start=55
  _globals['_COLLECTIONMETA']._serialized_end=85
  _globals['_CREATECOLLECTIONSREQUEST']._serialized_start=87
  _globals['_CREATECOLLECTIONSREQUEST']._serialized_end=160
  _globals['_CREATECOLLECTIONSRESPONSE']._serialized_start=162
  _globals['_CREATECOLLECTIONSRESPONSE']._serialized_end=277
  _globals['_DELETECOLLECTIONSREQUEST']._serialized_start=279
  _globals['_DELETECOLLECTIONSREQUEST']._serialized_end=320
  _globals['_DELETECOLLECTIONSRESPONSE']._serialized_start=322
  _globals['_DELETECOLLECTIONSRESPONSE']._serialized_end=406
  _globals['_LISTCOLLECTIONSREQUEST']._serialized_start=408
  _globals['_LISTCOLLECTIONSREQUEST']._serialized_end=466
  _globals['_LISTCOLLECTIONSRESPONSE']._serialized_start=468
  _globals['_LISTCOLLECTIONSRESPONSE']._serialized_end=578
# @@protoc_insertion_point(module_scope)
