# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arike_auth.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'arike_auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import arikedb.arike_utils_pb2 as arike__utils__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61rike_auth.proto\x12\x08\x61rike_pb\x1a\x11\x61rike_utils.proto\"9\n\x13\x41uthenticateRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"K\n\x14\x41uthenticateResponse\x12$\n\x06status\x18\x01 \x01(\x0e\x32\x14.arike_pb.StatusCode\x12\r\n\x05token\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arike_auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATEREQUEST']._serialized_start=49
  _globals['_AUTHENTICATEREQUEST']._serialized_end=106
  _globals['_AUTHENTICATERESPONSE']._serialized_start=108
  _globals['_AUTHENTICATERESPONSE']._serialized_end=183
# @@protoc_insertion_point(module_scope)
