name: Upload Python Package

on:
  push: 
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: python -m pip install --upgrade pip wheel setuptools twine
    - name: Build package
      run: python setup.py bdist_wheel
    - name: Publish package
      env:
        TWINE_PASSWORD: ${{ secrets.TWINE_API_KEY }}
      run: |
        twine upload dist/*
